# Generated by Django 4.2.7 on 2023-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
