# Generated by Django 4.2.7 on 2023-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
