# Generated by Django 4.2.7 on 2023-12-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
