# Generated by Django 4.2.7 on 2023-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
