# Generated by Django 4.2.7 on 2023-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_product_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
