# Generated by Django 4.2.7 on 2023-12-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_products_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
